apiVersion: apps/v1
kind: Deployment
metadata:
  name: chandansrazuredevopscipipeline-nginx-deployment
  labels:
    app: chandansrazuredevopscipipeline-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chandansrazuredevopscipipeline-nginx
  template:
    metadata:
      labels:
        app: chandansrazuredevopscipipeline-nginx
    spec:
      containers:
        - name: askcontainerdt-nginx  # Corrected name
          image: askcontainerdt.azurecr.io/chandansrazuredevopscipipeline:106
          ports:
            - containerPort: 80
      imagePullSecrets:                # Corrected placement
        - name: dev-secret
---
apiVersion: v1
kind: Service
metadata:
  name: app1-nginx-loadbalancer-service
  labels:
    app: app1-nginx
spec:
  type: LoadBalancer
  selector:
    app: app1-nginx
  ports:
    - port: 80
      targetPort: 80
